name: Install R + pak
description: |
  Install R and dependencies with pak
inputs:
  r-version:
    description: "The version of R to install"
    default: "release"
  http-user-agent:
    default: ""
  use-public-rspm:
    default: true
  packages-file:
    default: ""
    description: "File with content to pass to the `extra-packages` argument of setup-r-dependencies"
  extra-packages:
    default: ""
    description: "More packages to install in addition to those specified in `packages-file`"

runs:
  using: "composite"
  steps:
    - uses: r-lib/actions/setup-pandoc@v2

    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ inputs.r-version }}
        http-user-agent: ${{ inputs.http-user-agent }}
        use-public-rspm: ${{ inputs.use-public-rspm }}


    - name: Set package versions
      shell: bash
      run: |
        # get package versions from file
        if [ -f ${{ inputs.packages-file }} ]; then
          PKG_VERSIONS=$(cat ${{ inputs.packages-file }})
        fi

        # get additional package versions from input
        if [ "${{ inputs.extra-packages }}" ]; then
          if [ "$PKG_VERSIONS" ]; then
            PKG_VERSIONS="${PKG_VERSIONS}, ${{ inputs.extra-packages }}"
          else
            PKG_VERSIONS="${{ inputs.extra-packages }}"
          fi
        fi

        echo $PKG_VERSIONS
        echo "PKG_VERSIONS=${PKG_VERSIONS}" >> "$GITHUB_ENV"

    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: "${{ env.PKG_VERSIONS }}"

