name: Install R
description: |
  Install R and dependencies
inputs:
  r-version:
    description: "The version of R to install"
    default: "4.5.1"
  renv-profile:
    default: '"dev"'
  http-user-agent:
    default: ""
  use-public-rspm:
    default: true

runs:
  using: "composite"
  steps:
    - name: install ubuntu deps
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev pandoc

    - uses: r-lib/actions/setup-pandoc@v2

    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ inputs.r-version }}
        http-user-agent: ${{ inputs.http-user-agent }}
        use-public-rspm: ${{ inputs.use-public-rspm }}

    - uses: r-lib/actions/setup-renv@v2
      with:
        profile: '${{ inputs.renv-profile }}'
